name: docker build and push

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

run-name: Build and push docker image

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build image and push to docker hub
        run: |
          docker buildx build --push \
            --tag stroebs/dn42-pingfinder:latest  \
            --platform linux/arm/v7 .

      - name: build image and push to docker hub
        run: |
          docker buildx build --push \
            --tag stroebs/dn42-pingfinder:latest  \
            --platform linux/arm/v7,linux/amd64,linux/arm64 .
